default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: db

development:
  <<: *default
  database: hands_on_segfy_development

test:
  <<: *default
  database: hands_on_segfy_test

production:
  <<: *default
  database: hands_on_segfy_production
  username: hands_on_segfy
  password: <%= ENV["HANDS_ON_SEGFY_DATABASE_PASSWORD"] %>
